src/Resources/config/doctrine/Page.orm.yml, src/Resources/config/routing.yml
- Change association to ProductInterface in Page.yml.orm https://github.com/bitbag-commerce/CmsPlugin/issues/11 
- Add locale to bitbag_cms_shop_page_show route
=> Change Page.yml.orm and routing.yml 

src/Resources/views/Page/show.html.twig
When you add a product, then remove it, the resource.products array exists but is empty. Therefore it isn't equal to null.
=> Check as well if array exists, that it is not empty

src/Form/Type/FrequentlyAskedQuestionType.php, src/Resources/translations/messages.en.yml, src/Resources/translations/messages.nl.yml, src/Resources/translations/validators.nl.yml
Due to issue #97 using a English cms user wasn't an option for the time being so i decided to update the Dutch translations and found the FAQ form type hadn't been translated. I based the 'messages' translation on the English translation file and tossed out all the stuff that wasn't in there to prevent unused translations being present.
=> added FAQ from translations and updated nl translation

tests/Application/app/config/fixtures.yml
Fixed url route typo in fixtures, used for https://demo.bitbag.shop/
=> Fix route typo in fixtures

src/Resources/config/grids/admin/page.yml
Fix a wrong configuration in the declaration of the Page resource, causing an 500 error when searching a page in admin. The `type` field does not exists in the entity, it should be removed.
| Related tickets | fixes #140 
=> Fix a wrong configuration in the Page resource

UPGRADE.md, spec/Entity/PageSpec.php, spec/EventListener/PageImageUploadListenerSpec.php, spec/Resolver/PageResourceResolverSpec.php, spec/Twig/Extension/RenderProductPagesExtensionSpec.php, src/Controller/MediaController.php, src/Controller/PageController.php, src/Entity/Page.php, src/Entity/PageInterface.php, src/EventListener/PageImageUploadListener.php, src/Fixture/Factory/BlockFixtureFactory.php, src/Fixture/Factory/MediaFixtureFactory.php, src/Fixture/Factory/PageFixtureFactory.php, src/Fixture/MediaFixture.php, src/Importer/PageImporter.php, src/Repository/PageRepository.php, src/Repository/PageRepositoryInterface.php, src/Resolver/PageResourceResolver.php, src/Resolver/PageResourceResolverInterface.php, src/Resources/config/services/fixture.yml, src/SitemapProvider/PageUrlProvider.php, src/Twig/Extension/RenderMediaExtension.php, src/Twig/Extension/RenderProductPagesExtension.php, tests/Application/app/Resources/SyliusShopBundle/views/Homepage/index.html.twig, tests/Application/app/config/fixtures.yml, tests/Behat/Context/Setup/PageContext.php
=> Prepare 2.0.0 release

src/Twig/Parser/ContentParser.php
| Related tickets | fixes #192
Hi,
According to #192, I updated the parser to allow more than one function call in content of CMS pages.
I didn't write the tests because:
- Change of the fixtures is required I think.
- Should be tested in `\spec\BitBag\SyliusCmsPlugin\Twig\Parser\ContentParserSpec::it_parses_string_functions`.
- No time? 😄 
So, of course allow you to update the PR to make this fix a reality. I did that in my fork to go forward and avoid being blocked. Feel free! I can help in any way, I'm on Slack also.
=> Improve the parser method to allow multiple function calls

src/Resources/config/routing/admin/block.yml, src/Resources/config/routing/admin/frequently_asked_question.yml, src/Resources/config/routing/admin/media.yml, src/Resources/config/routing/admin/page.yml, src/Resources/config/routing/admin/section.yml
Some template path defined in route config is using legacy naming style. It prevents to override admin templates from a Symfony flex project.
=> Fix template path in controllers config

src/Resources/config/doctrine/Page.orm.yml
A page could not be deleted if linked to a product or a section, resulting in a FK error thrown by the DB.
I noticed an invalid name for the join column of the section association (block_id instead of page_id, see line 51) but did not change it for BC
=> Fix Page mapping to cascade delete product association

features/admin/adding_block.feature, spec/Entity/BlockTranslationSpec.php, spec/Entity/MediaTranslationSpec.php, src/Entity/Media.php, src/Entity/MediaInterface.php, src/Entity/MediaTranslation.php, src/Entity/MediaTranslationInterface.php, src/Fixture/Factory/MediaFixtureFactory.php, src/Fixture/MediaFixture.php, src/Form/Type/Translation/BlockTranslationType.php, src/Form/Type/Translation/MediaTranslationType.php, src/Resources/config/doctrine/MediaTranslation.orm.yml, src/Resources/config/routing/shop/media.yml, src/Resources/config/validation/BlockTranslation.yml, src/Resources/config/validation/MediaTranslation.yml, src/Resources/translations/validators.en.yml
- Added links to media-image: I wan't to create sections where I add media-images with "promotions" pictures that links to a page. But I also wan't to be able to add overlay content to that media-image.
- Added links to blocks: I guess that either blocks had links enabled before and got removed, or they never got implemented in the block form.
- Removed not-blank validation from blocks: Now when I added links to blocks I would like to create sections with link-blocks. Like columns with links in the footer of a website. Therefor I need the option to create blocks without any content.
- Added a route for media with variable template: I needed a way to get medias with a custom template.
| BC …
=> Links for media and blocks, update of validation for blocks and new route for custom template for medias

src/Resources/translations/validators.fr.yml
`validators.fr.yml` was missing some strings, I completed it based on `validators.en.yml`
=> Add missing FR translations

src/Repository/BlockRepository.php, src/Repository/FrequentlyAskedQuestionRepository.php, src/Repository/PageRepository.php, src/Repository/PageRepositoryInterface.php, src/Repository/SectionRepository.php, src/Repository/SectionRepositoryInterface.php, src/Resources/config/grids/admin/block.yml, src/Resources/config/grids/admin/section.yml, src/Resources/views/Grid/Field/sections.html.twig
| BC breaks?      | no/
- Fixed an issue in admin with getting being able to see elements without an existing for locale of current admin user.
- Also removed the `content` field from the block overview. If you would have a large text, it would screw up the whole admin page.
=> Fixed problem with innerJoin on translation that not exist

src/Resources/config/grids/admin/block.yml
It's a one line fix.
I just removed the `type` field in filters because blocks don't have type… it was leading to broken filters in admin.
Cheers!
=> Do not filter on type field because it doesn't exist

src/Resources/config/grids/shop/page.yml
| Related tickets |
Otherwise the sorting does not work. 
```
sorting:
createdAt: desc
```
As indicated from this sorting definition, the newest pages are supposed to show up first.
=> Set field createdAt as sortable on shop_page grid

doc/importing-resources.md, doc/installation.md, src/DependencyInjection/Compiler/ImporterCompilerPass.php, src/Resources/config/services/importer.yml
Import/export plugin use the same tag name as `bitbag.importer` but the different interface for importer classes.
After running `bin/console cache:clear` container build fail because compiler pass gets all services with tag name bitbag.importer.
In this fix the tag name `bitbag.importer` is replaced to `bitbag.cmsplugin.importer`
=> Fix conflict with import/export plugin.

doc/fixtures.md
This PR fixes a broken link on the documentation for Fixtures
=> Fix broken link on Fixtures documentation

src/Repository/PageRepository.php, src/Resources/config/grids/admin/page.yml
This feature adds a Section filter to the Pages grid by default.
=> Add Section filter to Pages grid

.travis.yml
Added a matrix to Travis for test the previous (and current) versions of Sylius.
Currently, tests are only run on Sylius 1.6.1.
=> travis Sylius multi versions

src/Controller/Helper/FormErrorsFlashHelper.php
| Related tickets | N/A
Hello, 
The FormHerrorsFlashHelper use `implode` function with a deprecated signature, and this is not more available in PHP8. 
This PR fix the signature use :slightly_smiling_face:
=> Fix correct signature of implode

src/Resources/config/resources/block.yml, src/Resources/config/resources/frequently_asked_question.yml, src/Resources/config/resources/media.yml, src/Resources/config/resources/page.yml, src/Resources/config/resources/section.yml
Default resource factory for translatable entity should be TranslatableFactory.
=> Resource factory changed to TranslatableFactory

src/Resources/assets/admin/js/bitbag/bitbag-page-slug.js
While creating/editing a page name in admin panel (`/admin/pages`), if it contains ampersand symbol (`&`), the generated slug should contain all typed letters and remove only ampersand (or other symbols) from it.
Example:
Whole part after ampersand is cut off from slug.
Example:
As `&` is a special character in URLs, values containing it must be encoded while passing it as query parameter.
=> Bug fix: Slug generation for values containing ampersand symbol

src/Controller/MediaController.php
Fix of error :
```
request.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\LogicException: "Cannot check if an unsubmitted form is valid. Call Form::isSubmitted() before Form::isValid()." at /home/site/vendor/symfony/form/Form.php line 765 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\LogicException(code: 0): Cannot check if an unsubmitted form is valid. Call Form::isSubmitted() before Form::isValid(). at /home/site/vendor/symfony/form/Form.php:765)"} []
```
=> Fix form error

features/admin/adding_page.feature, features/shop/displaying_page.feature, spec/Resolver/BlockResourceResolverSpec.php, src/Entity/Page.php, src/Entity/PageInterface.php, src/Form/Type/PageType.php, src/Migrations/Version20240725064430.php, src/Resolver/BlockResourceResolver.php, src/Resources/assets/admin/js/bitbag/bitbag-page-slug.js, src/Resources/config/doctrine/Page.orm.xml, src/Resources/config/services/resolver.xml, src/Resources/config/validation/PageTranslation.xml, src/Resources/views/Page/Crud/_form.html.twig, tests/Application/templates/bundles/SyliusShopBundle/layout.html.twig
=> OP-442: Locales functionality

features/admin/adding_block.feature, features/admin/adding_template.feature, spec/Menu/ContentManagementMenuBuilderSpec.php, spec/Menu/MenuReorderSpec.php, src/Form/Type/BlockType.php, src/Form/Type/TemplateBlockAutocompleteChoiceType.php, src/Form/Type/TemplateType.php, src/Menu/ContentManagementMenuBuilder.php, src/Menu/MenuReorder.php, src/Menu/MenuReorderInterface.php, src/Resources/assets/admin/js/bitbag/bitbag-template.js, src/Resources/config/routing/admin/template.yml, src/Resources/config/services/event_listener.xml, src/Resources/config/services/menu.xml, src/Resources/views/Block/Crud/_form.html.twig, src/Resources/views/Form/theme.html.twig, src/Resources/views/Page/Crud/_form.html.twig, src/Resources/views/Template/form.html.twig, tests/Behat/Context/Ui/Admin/BlockContext.php, tests/Behat/Page/Admin/Block/CreatePage.php, tests/Behat/Page/Admin/Block/CreatePageInterface.php, tests/Behat/Page/Admin/Page/CreatePageInterface.php, tests/Behat/Resources/suites/ui/managing_blocks.yml, tests/Integration/DataFixtures/ORM/TemplateRepositoryTest/test_it_finds_template_by_name.yml, tests/Integration/Repository/TemplateRepositoryTest.php
=> OP-463: Block templates

features/admin/adding_block.feature, features/admin/adding_template.feature, spec/Menu/ContentManagementMenuBuilderSpec.php, src/Entity/Page.php, src/Entity/PageTranslation.php, src/Form/Type/BlockType.php, src/Form/Type/TemplateBlockAutocompleteChoiceType.php, src/Form/Type/TemplateType.php, src/Menu/ContentManagementMenuBuilder.php, src/Renderer/ContentElement/ProductsCarouselByTaxonContentElementRenderer.php, src/Renderer/ContentElement/ProductsCarouselContentElementRenderer.php, src/Renderer/ContentElement/ProductsGridByTaxonContentElementRenderer.php, src/Renderer/ContentElement/SingleMediaContentElementRenderer.php, src/Resources/assets/admin/js/bitbag/bitbag-template.js, src/Resources/config/routing/admin/template.yml, src/Resources/views/Block/Crud/_form.html.twig, src/Resources/views/Form/theme.html.twig, src/Resources/views/Page/Crud/_form.html.twig, src/Resources/views/Template/form.html.twig, tests/Behat/Context/Ui/Admin/BlockContext.php, tests/Behat/Page/Admin/Block/CreatePage.php, tests/Behat/Page/Admin/Block/CreatePageInterface.php, tests/Behat/Page/Admin/Page/CreatePageInterface.php, tests/Behat/Resources/suites/ui/managing_blocks.yml, tests/Integration/DataFixtures/ORM/TemplateRepositoryTest/test_it_finds_template_by_name.yml, tests/Integration/Repository/TemplateRepositoryTest.php
=> OP-462: Page preview functionality

doc/block.csv, doc/page.csv, spec/Assigner/LocalesAssignerSpec.php, spec/Assigner/ProductsInTaxonsAssignerSpec.php, spec/Importer/BlockImporterSpec.php, spec/Importer/PageImporterSpec.php, spec/Resolver/ImporterLocalesResolverSpec.php, spec/Resolver/ImporterProductsInTaxonsResolverSpec.php, spec/Resolver/ImporterTaxonsResolverSpec.php, src/Assigner/LocalesAssigner.php, src/Assigner/LocalesAssignerInterface.php, src/Assigner/ProductsInTaxonsAssigner.php, src/Assigner/ProductsInTaxonsAssignerInterface.php, src/Command/ImportFromCsvCommand.php, src/Importer/BlockImporter.php, src/Importer/BlockImporterInterface.php, src/Importer/PageImporter.php, src/Importer/PageImporterInterface.php, src/Resolver/ImporterCollectionsResolver.php, src/Resolver/ImporterLocalesResolver.php, src/Resolver/ImporterLocalesResolverInterface.php, src/Resolver/ImporterProductsInTaxonsResolver.php, src/Resolver/ImporterProductsInTaxonsResolverInterface.php, src/Resolver/ImporterTaxonsResolver.php, src/Resolver/ImporterTaxonsResolverInterface.php, src/Resources/config/services/assigner.xml, src/Resources/config/services/importer.xml, src/Resources/config/services/resolver.xml
=> OP-464: Block and page import adjustments
