src/Resources/translations/messages.es.yml, src/Resources/translations/validators.es.yml
Added spanish translations files
=> Added spanish translations

src/Resources/translations/messages.de.yml
=> German Messages Language Version

src/Resources/config/doctrine/Block.orm.yml, src/Resources/config/doctrine/Page.orm.yml, tests/Behat/Context/Setup/BlockContext.php
We already have uniqueness validation for codes
=> Enforce code uniqueness on database level as well

src/Resources/translations/messages.nl.yml, src/Resources/translations/validators.nl.yml
=> add NL translation

README.md
updating database schema and installing assets must be done after enabling and configuring the bundle
=> correct order of installation steps

composer.json
=> [Composer] Rename branch alias

.gitignore, composer.lock
=> Add composer lock

src/Repository/SectionRepository.php, src/Resources/config/routing/admin/section.yml
| Related tickets | fixes #97 
=> Do not rely on admin's locale for section autocomplete

src/Controller/Action/Admin/ProductSearchAction.php, src/Repository/ProductRepository.php, src/Repository/ProductRepositoryInterface.php, src/Resources/config/routing/admin.yml, src/Resources/config/routing/admin/product.yml, src/Resources/config/services.yml, src/Resources/config/services/controller.yml, src/Resources/config/services/repository.yml, src/Resources/views/Form/theme.html.twig
| Related tickets | fixes #97 
=> Do not rely on admin's locale for product autocomplete

src/Resources/translations/messages.hr.yml, src/Resources/translations/validators.hr.yml
=> added croatian translations

src/Fixture/BlockFixture.php, src/Fixture/Factory/PageFixtureFactory.php, src/Fixture/FrequentlyAskedQuestionFixture.php, src/Fixture/PageFixture.php, src/Fixture/SectionFixture.php, src/Resources/config/services/fixture.yml, tests/Application/app/config/fixtures.yml
=> added image for blog fixtures

src/Form/Type/Translation/FrequentlyAskedQuestionTranslationType.php
=> Ability to translate FAQ form labels

src/Resources/config/grids/admin/block.yml, src/Resources/config/grids/admin/frequently_asked_question.yml, src/Resources/config/grids/admin/page.yml, src/Resources/config/grids/admin/section.yml
=> Added bulk delete

src/Controller/BlockController.php
| Related tickets | fixes #149
=> Make use of user provided template for block rendering (fixes #149)

src/Repository/ProductRepository.php, src/Repository/SectionRepository.php
=> Added more descriptive type hints to private methods to prevent errors later

src/Resources/translations/messages.es.yml, src/Resources/translations/validators.es.yml
=> Update Spanish translations

spec/Twig/Extension/RenderBlockExtensionSpec.php, src/Twig/Extension/RenderBlockExtension.php
| Related tickets | fixes #148
=> Add template argument to bitbag_cms_render_block twig function (closes #148)

src/Resources/public/js/bitbag-page-slug.js, src/Resources/views/Macro/translationForm.html.twig, src/Resources/views/Page/Crud/_form.html.twig, src/Resources/views/Page/create.html.twig
| Related tickets | fixes #137 
=> fixed slug generation and image preview #137

src/Controller/BlockController.php
=> Make use of user provided template for block rendering if provided (fixes #149) to v1.2.3 branch

composer.json
=> Change version alias

CHANGELOG.md, spec/Entity/MediaSpec.php, spec/Entity/SectionSpec.php, src/Controller/Action/Admin/ImportDataAction.php, src/Downloader/ImageDownloader.php, src/Entity/Media.php, src/Entity/MediaInterface.php, src/Entity/Section.php, src/Entity/SectionInterface.php, src/Fixture/Factory/MediaFixtureFactory.php, src/Fixture/Factory/SectionFixtureFactory.php, src/Form/Type/MediaType.php, src/Form/Type/SectionType.php, src/Repository/MediaRepository.php, src/Repository/MediaRepositoryInterface.php, src/Repository/SectionRepository.php, src/Repository/SectionRepositoryInterface.php, src/Resolver/MediaResourceResolver.php, src/Resources/config/doctrine/Block.orm.yml, src/Resources/config/doctrine/Media.orm.yml, src/Resources/config/doctrine/Page.orm.yml, src/Resources/config/doctrine/Section.orm.yml, src/Resources/config/routing/shop/media.yml, src/Resources/config/routing/shop/section.yml, src/Resources/config/services/controller.yml, src/Resources/config/services/fixture.yml, src/Resources/config/services/resolver.yml, src/Resources/views/Media/Crud/_form.html.twig, src/Resources/views/Section/Crud/_form.html.twig, tests/Behat/Context/Setup/SectionContext.php
=> Add channel awareness to media

doc/installation.md
=> [README] Fix formatting

doc/customization.md
Just adds 'How to disable localised URLs?' guide from #182 issue
=> Add 'How to disable localised URLs?' guide

doc/customization.md
Previous command only shows a subset (on my system), this command shows me the full list.
=> Generate full list of services available

doc/medias.md
| BC breaks?      | no/yes
Documentation update
=> update documentation - list media by specific section

src/Resources/config/services/sitemap_provider.yml, src/SitemapProvider/SectionUrlProvider.php, tests/Api/Sitemap/Provider/SitemapPageControllerApiTest.php, tests/Api/Sitemap/Provider/SitemapSectionControllerApiLocalesTest.php, tests/Api/Sitemap/Provider/SitemapSectionControllerApiTest.php, tests/Responses/Expected/show_sitemap_sections.xml, tests/Responses/Expected/show_sitemap_sections_locale.xml
=> [1.4] Add sitemap provider for sections

doc/sitemap.md, src/Resources/config/services.yml, src/SitemapProvider/SectionUrlProvider.php, tests/Api/Sitemap/Provider/SitemapPageControllerApiTest.php, tests/Api/Sitemap/Provider/SitemapSectionControllerApiLocalesTest.php, tests/Api/Sitemap/Provider/SitemapSectionControllerApiTest.php, tests/Responses/Expected/show_sitemap_sections.xml, tests/Responses/Expected/show_sitemap_sections_locale.xml
=> [2.0] Add sitemap provider for sections

src/Resources/translations/messages.fr.yml
| Related tickets | nonce
Hi !
The French translation was not up to date.
I re-ordered entries based on the English translation and added the missing translations.
=> Update french translation

composer.json
=> Compatibility with symfony flex

src/Resources/config/doctrine/Page.orm.yml
Delete a page having at least a channel otherwise we have a db constraint error
=> Delete a page having at least a channel

composer.json, tests/Behat/Context/Ui/Admin/BlockContext.php, tests/Behat/Context/Ui/Admin/FrequentlyAskedQuestionContext.php, tests/Behat/Context/Ui/Admin/MediaContext.php, tests/Behat/Context/Ui/Admin/PageContext.php, tests/Behat/Context/Ui/Admin/SectionContext.php, tests/Behat/Page/Shop/FrequentlyAskedQuestion/IndexPage.php, tests/Behat/Page/Shop/FrequentlyAskedQuestion/IndexPageInterface.php, tests/Behat/Page/Shop/Page/IndexPage.php, tests/Behat/Page/Shop/Page/IndexPageInterface.php, tests/Behat/Page/Shop/Page/ShowPage.php, tests/Behat/Page/Shop/Page/ShowPageInterface.php
=> Compatibility with Sylius v1.3.4

composer.json, doc/customization.md, src/Controller/MediaController.php, src/Controller/PageController.php, src/Resources/config/config.yml
=> Fix web path

composer.json
| Bug fix?        | yes 
| Related tickets | fixes #210
=> Put matthiasnoback/symfony-config-test in require-dev

composer.json
Fix deps for matthiasnoback/symfony-config-test
Rename lakion to lchrusciel (@see Sylius/Sylius-standard)
Move sensiolabs/security-checker to require (@see Sylius/Sylius-standard)
| Related tickets | fixes #210 
=> Fix deps for matthiasnoback/symfony-config-test

src/Resources/config/doctrine/PageImage.orm.yml, src/Resources/config/doctrine/PageTranslation.orm.yml, src/Resources/config/resources/page.yml
| Related tickets | fixes #191 
=> Fix PageImage mapping and association towards PageTranslation

doc/installation.md
Updated installation.md to cover Sylius 1.3.5 and Symfony 4.2 changes.
| Related tickets | fixes #227 
=> Updated installation.md

src/Resources/views/layout.html.twig
https://github.com/symfony/symfony/issues/25661#issuecomment-355066552
=> Add possibility of overriding layout template

composer.json
| Related tickets | fixes #256
=> Support sylius 1.5

src/Repository/FrequentlyAskedQuestionRepository.php
=> Allow Repository extension

features/admin/adding_page.feature, features/shop/displaying_page.feature, spec/Entity/PageTranslationSpec.php, src/Entity/Page.php, src/Entity/PageInterface.php, src/Entity/PageTranslation.php, src/Entity/PageTranslationInterface.php, src/Form/Type/Translation/PageTranslationType.php, src/Resources/config/doctrine/PageTranslation.orm.yml, src/Resources/translations/messages.cs.yml, src/Resources/translations/messages.cs_CZ.yml, src/Resources/translations/messages.de.yml, src/Resources/translations/messages.en.yml, src/Resources/translations/messages.es.yml, src/Resources/translations/messages.fr.yml, src/Resources/translations/messages.hr.yml, src/Resources/translations/messages.nl.yml, src/Resources/translations/messages.pl.yml, src/Resources/translations/messages.ru.yml, src/Resources/views/Shop/Page/show.html.twig, tests/Behat/Context/Setup/PageContext.php, tests/Behat/Context/Ui/Shop/PageContext.php, tests/Behat/Page/Shop/Page/ShowPage.php, tests/Behat/Page/Shop/Page/ShowPageInterface.php
I added an option that allows for choosing and configuring a page title for pages. (As in <head><title></title></head>)
=> Adding option to set the page title

src/Controller/Action/Admin/UploadEditorImageAction.php, src/Resources/translations/validators.de.yml, src/Resources/translations/validators.en.yml, src/Resources/translations/validators.es.yml, src/Resources/translations/validators.fr.yml, src/Resources/translations/validators.hr.yml, src/Resources/translations/validators.nl.yml, src/Resources/translations/validators.pl.yml, src/Resources/translations/validators.ru.yml
Allow to import SVG images file.
=> add svg image support

composer.json
=> Update league/csv package to 9.1

composer.json
| Related tickets | fixes #277 
=> move sensiolabs/security-checker to composer-dev

src/Entity/PageInterface.php
=> Add SlugAwareInterface for Page entity

src/Downloader/ImageDownloader.php
=> Fixes issue with incorrect temp file path

src/Resources/config/doctrine/Media.orm.yml
| Related tickets | fixes https://github.com/BitBagCommerce/SyliusCmsPlugin/issues/252
=> Add missing onDelete action to Media.orm.yml

src/Resources/translations/messages.lt.yml, src/Resources/translations/validators.lt.yml
=> Add Lithuanian translation

src/Resources/config/routing/shop/page.yml
=> Remove empty argument

composer.json
| New feature?    | not really
| BC breaks?      | dont think so looking at release notes of bundle
=> Allow installation of FOSCKEditorBundle ^2.0

doc/installation.md
As indicated here : https://github.com/FriendsOfSymfony/FOSCKEditorBundle/blob/2.x/UPGRADE-2.0.md
=> [doc] installation with FOSCKEditorBundle 2.0

doc/installation.md, src/Resources/config/services.yml, src/Resources/config/services/sitemap_provider.yml, tests/Application/config/services.yaml
| BC breaks?      | yes
| Related tickets | #308 
=> make sitemap providers optional

src/Resources/public/js/bitbag-cms-resource-preview.js
Removed duplication, changed data url to blob url  - to fix CORS issues with preview
=> Removed duplication, changed data url to blob url 

src/Resources/views/Shop/FrequentlyAskedQuestion/index.html.twig
=> Add support for Schema.org/FAQPage on FAQ shop page

src/Entity/Block.php, src/Resources/config/routing/admin/block.yml, src/Resources/config/routing/admin/media.yml, src/Resources/config/routing/admin/page.yml
| Related tickets | fixes #306,  #307, 
=> Fix for #306,  #307

src/Resources/views/CrudUi/create.html.twig, src/Resources/views/CrudUi/index.html.twig, src/Resources/views/CrudUi/update.html.twig, src/Resources/views/Shop/Page/index.html.twig, src/Resources/views/layout.html.twig
=> Fix templates namespaces to make them compatible with the newer Symfony

.travis.yml, features/admin/adding_page.feature, features/admin/managing_pages.feature, src/Repository/MediaRepository.php, src/Repository/MediaRepositoryInterface.php, src/Resources/config/routing/admin/media.yml, tests/Behat/Context/Setup/MediaContext.php, tests/Behat/Context/Ui/Admin/PageContext.php, tests/Behat/Page/Admin/Page/CreatePage.php, tests/Behat/Page/Admin/Page/CreatePageInterface.php, tests/Behat/Page/Admin/Page/UpdatePage.php, tests/Behat/Page/Admin/Page/UpdatePageInterface.php, tests/Behat/Resources/suites/ui/managing_pages.yml, tests/Behat/Service/FormHelper.php
=> Update tests for switch MediaInterface page images

src/Controller/MediaController.php, src/Entity/Media.php, src/Entity/MediaInterface.php, src/MediaProvider/FilenameHelper.php, src/Repository/MediaRepository.php, src/Repository/MediaRepositoryInterface.php, src/Resources/config/routing/admin/media.yml, src/Resources/config/routing/shop/media.yml
=> Add route for getting inline media by code

src/Entity/Page.php
| Related tickets | fixes #319
=> Page createTranslation compatible with TranslatableTrait

spec/Twig/Parser/ContentParserSpec.php, src/Twig/Parser/ContentParser.php
| Related tickets | fixes #325
=> change reggex

UPGRADE.md, src/Entity/Media.php, src/Entity/MediaInterface.php, src/Resources/config/doctrine/Media.orm.yml, src/Resources/views/Shop/Media/Show/image.html.twig, src/Uploader/MediaUploader.php
| Related tickets | fixes #262
=> image width and height attribute

src/Resources/config/config.yml
| Related tickets | fixes #281
=> fix page thumbnails in pages list

spec/Twig/Extension/RenderBlockExtensionSpec.php, spec/Twig/Extension/RenderMediaExtensionSpec.php, src/Resources/config/services/twig.yml, src/Twig/Extension/RenderBlockExtension.php, src/Twig/Extension/RenderMediaExtension.php
=> this not object context when use twig function in ckeditor fix 

.travis.yml
=> upgrade travis to php 7.4

src/Resources/config/doctrine/Page.orm.yml, src/Resources/translations/messages.en.yml, src/Resources/translations/messages.pl.yml, src/Resources/views/Page/Crud/_form.html.twig, src/Resources/views/Shop/Page/Error/_notPublished.html.twig, src/Resources/views/Shop/Page/show.html.twig
=> fix publish at

doc/installation.md
=> sitemap installation

composer.json, ecs.php, src/Form/Type/Translation/MediaTranslationType.php, src/Resources/config/validation/Media.yml, src/Resources/translations/validators.en.yml, src/Resources/translations/validators.pl.yml, src/Validator/Constraint/FileMatchesType.php, src/Validator/FileMatchesType.php, src/Validator/FileMatchesTypeValidator.php, tests/Application/config/routes/dev/twig.yaml
=> Media file and type validation

src/Resources/config/fos_ck_editor/fos_ck_editor.yml
Change enterMode to use div's instead of p's, paste HTML as plain text, save formatting from MS-word
=> OPSRC-183 - Change CKEditor default settings

src/Resources/config/api_resources/Block.xml, src/Resources/config/api_resources/Faq.xml, src/Resources/config/api_resources/Media.xml, src/Resources/config/api_resources/Page.xml, src/Resources/config/api_resources/Section.xml, src/Resources/config/serialization/Block.xml, src/Resources/config/serialization/BlockTranslation.xml, src/Resources/config/serialization/Faq.xml, src/Resources/config/serialization/FaqTranslation.xml, src/Resources/config/serialization/Media.xml, src/Resources/config/serialization/MediaTranslation.xml, src/Resources/config/serialization/Page.xml, src/Resources/config/serialization/PageTranslation.xml, src/Resources/config/serialization/Section.xml, src/Resources/config/serialization/SectionTranslation.xml
=> [added api platofrm resources]

src/Fixture/Factory/PageFixtureFactory.php, src/Fixture/PageFixture.php, src/Resources/views/Shop/Block/show.html.twig, src/Resources/views/Shop/Product/_pagesBySection.html.twig, tests/Application/config/packages/bitbag_sylius_cms_plugin.yml, tests/Application/templates/bundles/SyliusShopBundle/Product/show.html.twig, tests/Behat/Page/Shop/HomePage.php
=> OPSRC-188 - Add taxons and products to blocks and fix fixtures

src/Controller/MediaController.php
=> OPSRC-236 - Fix media preview page

src/Resources/public/css/style.css, src/Resources/public/js/bitbag-media-autocomplete.js, src/Resources/views/Form/theme.html.twig
=> OPSRC-181 - Add function to remove image from Page Image input

doc/media.md, spec/Twig/Runtime/RenderMediaRuntimeSpec.php, src/Resources/views/Shop/Media/Show/image.html.twig, src/Twig/Runtime/RenderMediaRuntime.php, tests/Application/config/packages/bitbag_sylius_cms_plugin.yml, tests/Application/templates/bundles/SyliusShopBundle/Homepage/index.html.twig, tests/Application/templates/examples/media_custom_template.html.twig
=> OPSRC-189 - Add optional template parameter with example

src/Resources/config/fos_ck_editor/fos_ck_editor.yml
=> Fix for disappearing iframes

src/Resolver/MediaResourceResolver.php, src/Resources/config/services/resolver.yml, tests/Application/config/sylius/1.10/packages/_sylius.yaml
=> Fix for media display

composer.json, src/EventListener/ResourceDeleteSubscriber.php, src/Resources/config/grids/admin/media.yml, src/Resources/config/services/event_listener.yml
=> Fix internal server error, when removing media with relation from Sylius grid

src/Importer/PageImporter.php, src/Importer/PageImporterInterface.php
=> Fix page importer missing values

src/Repository/MediaRepository.php, src/Repository/MediaRepositoryInterface.php, src/Resources/config/routing/shop/media.yml
=> Fix for media queries

src/Repository/MediaRepository.php, src/Repository/MediaRepositoryInterface.php, src/Resolver/MediaResourceResolver.php, src/Resources/config/routing/shop/media.yml, src/Resources/config/services/resolver.yml, tests/Behat/Context/Setup/MediaContext.php, tests/Behat/Context/Transform/MediaContext.php, tests/Behat/Resources/services/contexts/transform.yml
=> Fix media channel support

UPGRADE.md
| Related tickets | Resolves #369
=> Add missing information about the deprecation

doc/installation.md, doc/wysiwyg.md, src/Resources/views/Form/ckeditor_widget.html.twig, tests/Application/config/packages/twig.yaml
=> Update docs and fix CKEditor configuration

src/Resources/config/grids/admin/section.yml
=> Fix section filters

src/Resources/views/CrudUi/create.html.twig, src/Resources/views/CrudUi/update.html.twig, src/Resources/views/layout.html.twig, tests/Application/templates/bundles/SyliusShopBundle/layout.html.twig
=> fix reading unavaiable and not needed css

src/Fixture/Factory/PageFixtureFactory.php, src/Resources/config/services/fixture.yml
This PR fixes missing support for multiple channels in `PageFixtureFactory`.
=> Add support for multiple channels in PageFixtureFactory

src/Resources/translations/validators.cs.yml
| Related tickets | fixes #396
=> Add missing translation for file validators.cs.yml

.github/workflows/build.yml, .github/workflows/coding_standard.yml, composer.json, tests/Application/.env, tests/Application/Kernel.php, tests/Application/config/sylius/1.11/bundles.php, tests/Application/config/sylius/1.11/packages/_sylius.yaml, tests/Application/config/sylius/1.11/packages/dev/jms_serializer.yaml, tests/Application/config/sylius/1.11/packages/jms_serializer.yaml, tests/Application/config/sylius/1.11/packages/prod/jms_serializer.yaml, tests/Application/config/sylius/1.11/packages/security.yaml
This PR adds support for the newest Sylius 1.11.
PR covers such cases like:
- Update composer.json
- Update GitHub workflow
=> Sylius 1.11 support

src/Resources/assets/admin/js/bitbag/bitbag-media-autocomplete.js
=> thumbnail loading with debounce

behat.yml.dist, composer.json, phpstan.neon, tests/Application/config/sylius/1.9/packages/_sylius.yaml
This PR fixes github actions:
- composer conflict fix
- new behat configuration with socket_timeout
- phpstan memory leak fix 
=> Github actions fix

.github/workflows/build.yml, .github/workflows/coding_standard.yml
=> Add allow for the symfony/flex plugin in gha build

src/Resources/config/serialization/Block.xml
| Related tickets | fixes #443
=> ISSUE-443: fix serializable attribute name for Block entity

src/Validator/FileMatchesTypeValidator.php
| BC breaks?      | no/
| Related tickets | fixes [OPRSC-626](https://bitbag.atlassian.net/browse/OPSRC-626)
=> Correction of errors during video file validation

features/shop/displaying_media.feature, tests/Behat/Context/Ui/Shop/MediaContext.php, tests/Behat/Page/Shop/HomePageInterface.php, tests/Behat/Resources/services/contexts/ui.yml, tests/Behat/Resources/suites.yml, tests/Behat/Resources/suites/ui/shop_media.yml
=> Opsrc 281 cms automatic tests for rendering media with custom templates and values

src/Form/Type/WysiwygType.php, src/Resources/config/fos_ck_editor/fos_ck_editor.yml
=> fixes ckeditor token

src/Resources/config/grids/admin/media.yml, src/Resources/views/Grid/Field/image_preview.html.twig
| Related tickets | fixes #424 
=> [OPSRC-693]Add preview column in media management list

.github/workflows/build.yml, composer.json
=> Opsrc-688/build fix

composer.json, src/Controller/Action/Admin/ImportDataAction.php, src/Controller/Helper/FormErrorsFlashHelper.php, src/EventListener/ResourceDeleteSubscriber.php, src/Resources/config/services/controller.yml, src/Resources/config/services/event_listener.yml, tests/Application/templates/bundles/SyliusShopBundle/layout.html.twig
Here's some fixes to help make this compatible with 1.12. I haven't runs tests on this but it should at least help with the biggest issues if nothing else and save some time. Happy to fix other issues if needed.
=> 1.12 compatibility changes 

src/Resources/assets/admin/js/bitbag/bitbag-media-autocomplete.js
| Related tickets | mentioned in #428 
Fixes multiple option in media autocomplete
=> Fix sending multiple values in loadEditUrl and displaying them in form

src/Twig/Parser/ContentParser.php
=> Use Twig\Environment instead of Twig_Environment

doc/wysiwyg.md
| Related tickets | mentioned in #411 
=> add link in documentation to solved problems with wysywig

src/Entity/Page.php
=> Remove duplicate line

doc/installation.md
=> Update testing plugin docs

src/Resources/assets/admin/js/bitbag/bitbag-media-autocomplete.js, src/Resources/assets/admin/js/index.js
=> OP-152: Fix issues with broken build on webpack and node 14

doc/fixtures.md
=> OP-151 - adds update explaining usage of fixtures in more details

.github/workflows/build.yml, .github/workflows/coding_standard.yml
=> Add slack notifications on failed builds

doc/installation.md, src/DependencyInjection/BitBagSyliusCmsExtension.php, src/Migrations/Version20230524102024.php
=> MUL-246 - adds migration for cms plugin, updates installation config

composer.json
Conflict with "doctrine/orm": ">=2.15.2" removed, doctrine fixed bug in orm 2.15.3
=> Removed conflict from composer.json

src/Resources/translations/messages.de.yml
| New feature?    | no (more a TASK instead of a FEATURE)
**Description**
I added a few new german translations, and improved also some of the existing ones! 🙂
=> TASK: improve existing & add new translations for german language

src/Resources/assets/admin/scss/_css.scss
=> OP-435: Remove CKEditor version deprecation red modal

src/Form/Type/MediaType.php, src/Menu/ContentManagementMenuBuilder.php, src/Resources/config/grids/admin/block.yml, src/Resources/config/grids/admin/collection.yml, src/Resources/config/grids/admin/media.yml, src/Resources/config/grids/admin/page.yml, src/Resources/views/Block/Crud/_form.html.twig, src/Resources/views/Grid/Field/channels.html.twig, src/Resources/views/Media/Crud/_form.html.twig, src/Resources/views/Page/Crud/_form.html.twig
=> OP-329: Forms/elements consistency

src/Resources/assets/admin/js/bitbag/bitbag-cms-preview.js
- Corrected preview error with ckeditor
=> OP-491 - Corrected preview error with ckeditor

src/Resources/assets/admin/js/bitbag/bitbag-content-configuration.js
- CKEditor correctly displaying
- also corrected another bug which involved catching a non-existent element
=> OP-437 - CKEditor correctly displaying

src/Form/DataTransformer/ContentElementDataTransformerChecker.php, src/Form/Type/ContentElements/PagesCollectionContentElementType.php, src/Form/Type/ContentElements/ProductsCarouselByTaxonContentElementType.php, src/Form/Type/ContentElements/ProductsGridByTaxonContentElementType.php, src/Form/Type/ContentElements/SingleMediaContentElementType.php, src/Resources/config/services/form.xml
=> OP-494: Fix for error 500 when trying to edit block/page when associated element has been removed

UPGRADE-4.4.md
=> typo in UPGRADE-4.4.md
